#!/usr/bin/env python3
"""
Apply pending taxonomy changes generated by KeywordTaxonomyOrganizer.

Reads data/pending_taxonomy_changes.json, executes each decision, then
deletes the file on success. Review the JSON before running.

Operations:
  promote — set is_candidate=0; taxonomy placement left for manual review
  merge   — remap job references + add alias; uses existing merge functions
  delete  — remove candidate and its job references

Usage:
    python scripts/apply_taxonomy_changes.py           # dry run (shows what would change)
    python scripts/apply_taxonomy_changes.py --execute # apply changes
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))

from config.settings import PENDING_TAXONOMY_PATH
from db.operations import (
    discard_framework,
    discard_skill,
    mark_framework_promoted,
    mark_skill_promoted,
    merge_framework,
    merge_skill,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
logger = logging.getLogger("apply_taxonomy")


def main() -> None:
    p = argparse.ArgumentParser(description="Apply pending taxonomy changes.")
    p.add_argument("--execute", action="store_true", help="Apply changes (default: dry run)")
    args = p.parse_args()

    if not PENDING_TAXONOMY_PATH.exists():
        logger.error(f"No pending changes found at {PENDING_TAXONOMY_PATH}")
        sys.exit(1)

    plan = json.loads(PENDING_TAXONOMY_PATH.read_text(encoding="utf-8"))
    promote_list = plan.get("promote", [])
    merge_list   = plan.get("merge",   [])
    delete_list  = plan.get("delete",  [])

    dry = not args.execute
    mode = "DRY RUN" if dry else "EXECUTE"
    logger.info(f"=== Apply taxonomy changes ({mode}) ===")
    logger.info(f"  promote={len(promote_list)}, merge={len(merge_list)}, delete={len(delete_list)}\n")

    for entry in promote_list:
        logger.info(f"  PROMOTE [{entry['kind']}] (id={entry['id']}) {entry['name']!r}")
        if not dry:
            if entry["kind"] == "skill":
                mark_skill_promoted(entry["id"])
            else:
                mark_framework_promoted(entry["id"])

    for entry in merge_list:
        logger.info(
            f"  MERGE   [{entry['kind']}] (id={entry['id']}) {entry['name']!r}"
            f" → (id={entry['into_id']}) {entry['into_name']!r}"
        )
        if not dry:
            if entry["kind"] == "skill":
                merge_skill(entry["id"], entry["into_id"])
            else:
                merge_framework(entry["id"], entry["into_id"])

    for entry in delete_list:
        logger.info(f"  DELETE  [{entry['kind']}] (id={entry['id']}) {entry['name']!r}")
        if not dry:
            if entry["kind"] == "skill":
                discard_skill(entry["id"])
            else:
                discard_framework(entry["id"])

    if dry:
        logger.info(f"\nDry run complete. Re-run with --execute to apply.")
    else:
        PENDING_TAXONOMY_PATH.unlink()
        logger.info(f"\nDone. Removed {PENDING_TAXONOMY_PATH}.")
        logger.info("Run review_candidates.py to assign taxonomy placement to promoted entries.")


if __name__ == "__main__":
    main()
